### ISSUE TITLE
try catch issue on stateful services 

### ISSUE THREAD

**Issue by hendelali** [Vantiq/Contributions#21]
Hi

We are having a situation at TDG where the cluster is very unstable, we are constantly having problems and losing nodes, those nodes most of the times affects the stateful services we are running. 

We've been trying to write code like the following in the services to recover the state from those situations.

The problem we are having at the moment is that the try catch statement is not working as expected and is throwing the error attached in the image.

Any idea of what's going on with the try catch statement and why it doesn't catch the exception to continue the execution normally?

Thanks in advance.
```
try{
    
    var loaded = cache.get(farmId)
    
}catch(ex){
    loaded = false
}

if (!loaded)
{
    farmThresholds = select ONE from FarmThreshold where farmId == farmId
}
var returnThreshold = {}
var state = cache.compute(farmId, (key, currentValue) => {	
    if (!currentValue)
    {
        currentValue = {}
        currentValue.farmId = farmId
        currentValue.thresholds = farmThresholds
        log.info(stringify(currentValue))
    }
```

<img width="440" alt="Screen Shot 2022-03-08 at 11 11 33 AM" src="https://user-images.githubusercontent.com/11338271/157554720-765838fe-a7ba-4f7f-a1ea-814fbfab8fb9.png">

**Comment by sfitts** [comment]
Since this involves an issue with an active customer and also doesn't involve any of the contributions, this really isn't the right place to log this issue.

Probably the best thing to do would be to contact support (support@vantiq.com) and work with them on the issue, reproduction, etc...

Second best (by a large margin) would be to log an issue in the [Vantiq Issues](https://github.com/Vantiq/vantiq-issues) repo.  You'll need much more information than you provide here.

Also, based on a quick read of the information you did provide, I'm not sure that the conclusion you reach (that `try` isn't working) is correct.  You can write some simple VAIL to show that this isn't true and the use in the context of stateful services doesn't change how low level VAIL statements work.

That said -- you should definitely contact support and work the case with them.

**Comment by hendelali** [comment]
Thanks.
